/**
 * The figures the landing page is allowed to print.
 *
 * Every row here traces to `algobic-os/brand.md`, which records what was
 * verified at source on 2026-07-30 and, more usefully, what was not. Two
 * figures were retracted from that document on the same day for being
 * unverifiable. Neither appears here and neither ever should.
 *
 * `confidence` is the point of this file. A page with nothing shipped is asking
 * to be taken on trust, and the cheapest way to earn that is to mark down your
 * own best-sounding number in public. The 63-84% row is the most persuasive
 * statistic available to this brand and it is the one row rendered quiet,
 * because neither of its two published figures states a method.
 *
 * Rules for adding a row:
 * - Copy the figure exactly as `brand.md` states it. Never round, never widen.
 * - `source` names a publisher only where the docs name one. Where they record
 *   a verification date but no publisher, leave it out. Inventing an
 *   attribution is worse than admitting the gap.
 * - Anything the docs mark withdrawn, retracted or unverified does not go here
 *   under any label.
 */

export type Confidence = "verified" | "no-methodology";

export type Figure = {
  /** Rendered at display size. Kept as a string: ranges and ratios are facts. */
  readonly figure: string;
  /** Completes the sentence the figure starts. */
  readonly claim: string;
  /** Named publisher, where the source documents name one. */
  readonly source?: string;
  /** When the figure was checked, not when it was published. */
  readonly asOf: string;
  readonly confidence: Confidence;
  /** Required on anything not `verified`: what exactly is wrong with it. */
  readonly caveat?: string;
};

/** Checked at source on this date. Bump only when the figures are re-checked. */
const CHECKED = "30 Jul 2026";

export const WHY_NOW: readonly Figure[] = [
  {
    figure: "41-46%",
    claim: "of new code written globally is generated by AI.",
    asOf: CHECKED,
    confidence: "verified",
  },
  {
    figure: "4:1",
    claim:
      "People who build business applications without being developers, against professional developers. Roughly 100-120 million to 27.7 million.",
    asOf: CHECKED,
    confidence: "verified",
  },
  {
    figure: "70%",
    claim:
      "of new enterprise applications will use low-code or no-code by 2026, up from under 25% in 2020.",
    source: "Gartner",
    asOf: CHECKED,
    confidence: "verified",
  },
  {
    figure: "750+",
    claim:
      "no-code platforms exist. Almost none of them will tell you which one to start with.",
    asOf: CHECKED,
    confidence: "verified",
  },
  {
    figure: "63-84%",
    claim: "of AI app-builder users are said to have no coding background.",
    asOf: CHECKED,
    confidence: "no-methodology",
    caveat:
      "Two published figures, neither of which states a method. Directionally consistent, individually unreliable. It is the most useful number on this page and it is the one you should trust least.",
  },
] as const;
